name: energy-tools
summary: Energy Tools for Energy Star and ErP Lot 3 or Lot 26
adopt-info: energy-tools
base: core18

grade: stable
confinement: strict
license: GPL-3.0

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386

parts:
  energy-tools:
    source: .
    plugin: python
    parse-info: [setup.py]
    stage-packages:
      - ethtool
      - python3-debian
      - python3-xlsxwriter

apps:
  energy-tools:
    command: env LC_ALL=C.UTF-8 energy-tools
    plugs:
      - hardware-observe
      - home
      - mount-observe
